apiVersion: autoscaling/v1      
kind: HorizontalPodAutoscaler
metadata:
  name: hello 
  namespace: default
spec:
  scaleRef:
    kind: Deployment
    name: hello
    subresource: scale
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization:
    targetPercentage: 10
